version: '3.8'
services:
  backend:
    build:
      context: ./api
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    restart: unless-stopped

  frontend:
    build:
      context: ./newsapp
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped